### ISSUE TITLE
Práctica: Entrevista.

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-yce#1]
[Práctica 7-Equipo CYE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-yce/files/13221934/Practica.7-Equipo.CYE.pdf)

**Comment by Alvaro2-0** [comment]
Portada = 25%
Proceso = 25%
Ilustraciones = 25%
Resultados y conclusiones = 25%
Total= 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
